function Container(){this.containerClass="MosContainer";this.html=$("<div />");this.info=$("<div />");this.info.addClass("videoInfo");this.html.append(this.info);this.important=2;this.html.data("important",2);this.y=this.x=0;this.html.data("me",this);this.Content=Container.initialized=!0;Container.prototype.setSize=function(){this.html.trigger("containerResize")};Container.prototype.initContainer=function(){this.html.addClass(this.containerClass);this.html.addClass("ui-widget-content");this.html.resizable()};
Container.prototype.setImportant=function(b){this.important=b;this.html.data("important",b)};Container.prototype.setInfoContent=function(b){this.info.html(b)};Container.prototype.resetInfo=function(){this.info.html("")};!0==this.initialized&&this.initContainer()}
function Stream(b,a,d,e){this.streamClass="streamClass";this.link=b;this.infoContent=d;this.name=a;this.miniatureLink=e;Container.call(this);if("undefined"==typeof Stream.initialized)for(var g in Container.prototype)Stream.prototype[g]=Container.prototype[g];Stream.initialized=!0;Stream.prototype.displayContent=function(){content=$("<div />");content.html('<object id="#flashContent" type="application/x-shockwave-flash" data="http://10.99.19.242/epicast/index.swf" width="60%" height="70%" allowFullScreen="true"><param name="movie" value="http://10.99.19.242/epicast/index.swf" /><param name="wmode" value="transparent" /><p>Image ou texte alternatif</p></object>');
return content};this.init=function(){this.initContainer();this.html.addClass(this.streamClass);this.html.data("link",this.link);this.html.data("name",this.name);this.html.data("miniatureLink",this.miniatureLink);this.setInfoContent(this.infoContent);this.html.append('<img class="miniature" src="http://img.youtube.com/vi/'+this.link+'/0.jpg" />')};this.init()}
function Video(b,a,d,e){this.streamClass="videoClass";this.link=b;this.name=a;this.info=d;this.miniatureLink=e;Container.call(this);if("undefined"==typeof Video.initialized)for(var g in Container.prototype)Video.prototype[g]=Container.prototype[g];Video.initialized=!0;Video.prototype.displayContent=function(){content=$("<div />");content.html('<iframe width="1280" height="720" src="http://www.youtube.com/embed/'+this.link+'?rel=0" frameborder="0" allowfullscreen></iframe>');return content};this.init=
function(){this.initContainer();this.html.addClass(this.streamClass);this.html.data("link",this.link);this.html.data("name",this.name);this.html.data("miniatureLink",this.miniatureLink);this.setInfoContent(this.infoContent);this.html.append('<img class="miniature" src="http://img.youtube.com/vi/'+this.link+'/0.jpg" />')};this.init()}
function Folder(b){this.streamClass="folderClass";this.link=b;Container.call(this);if("undefined"==typeof Folder.initialized)for(var a in Container.prototype)Folder.prototype[a]=Container.prototype[a];Folder.initialized=!0;this.init=function(){this.initContainer();this.html.addClass(this.streamClass)};this.init()}
function setGrillEvent(){$(".grill").hover(function(){var b=$(this).data("x"),a=$(this).data("y");!0==$(this).data("parent").checkPlace(1,b,a)&&($(this).html('<img src="img/add.png" class="imgAdd" />'),$(".imgAdd").click(function(){$("#addContainer").show("clip",200)}))});$(".grill").mouseleave(function(){$(this).html("")});$("#addContainer").load("html/addContainer.html",function(){$("#addContainerMask").click(function(){$("#addContainer").hide("clip",200)})})}
function setEvent(){$(".MosContainer").draggable({revert:"invalid",zIndex:"2700",refreshPositions:!0,cursor:"crosshair"});$(".MosContainer").draggable({start:function(){idDrag=$(this).data("id");$(this).css("z-index","100")},end:function(){$(this).css("z-index","1")}});$(".grill").droppable({over:function(b,a){var d="grill-can-drop";$(this).data("x");$(this).data("parent").checkPlace(a.draggable.data("important"),$(this).data("x"),$(this).data("y"),a.draggable.data("id"))||(d="grill-cant-drop");for(id in $(this).data("parent").fence)$(this).data("parent").fence[id].data("x")>=
$(this).data("x")&&$(this).data("parent").fence[id].data("x")<a.draggable.data("important")+$(this).data("x")&&$(this).data("parent").fence[id].data("y")>=$(this).data("y")&&$(this).data("parent").fence[id].data("y")<a.draggable.data("important")+$(this).data("y")&&$(this).data("parent").fence[id].addClass(d)},out:function(){$(".grill").removeClass("grill-can-drop");$(".grill").removeClass("grill-cant-drop")},drop:function(b,a){$(this).data("parent").checkPlace(a.draggable.data("important"),$(this).data("x"),
$(this).data("y"),a.draggable.data("id"))?(a.draggable.data("parent").removeContainer(a.draggable.data("id")),a.draggable.data("x",$(this).data("x")),a.draggable.data("y",$(this).data("y")),$(this).data("parent").addContainer(a.draggable.data("me"))):$(".Mosaique").trigger("mosaiqueResize");$(".grill").removeClass("grill-can-drop");$(".grill").removeClass("grill-cant-drop");$(".Mosaique").trigger("mosaiqueResize")}});$(".MosContainer").droppable({drop:function(b,a){if(a.draggable.data("parent").checkPlace(a.draggable.data("important"),
$(this).data("x"),$(this).data("y"),a.draggable.data("id"))){alert("lol");var d=$(this).data("x"),e=$(this).data("y"),g=parseInt($(this).data("id"));a.draggable.data("parent");a.draggable.data("x",d);a.draggable.data("y",e);a.draggable.data("parent").removeContainer(g);$(".Mosaique").trigger("mosaiqueResize")}}});$(".MosContainer").on({click:function(){var b=new One_tabs;tab.add_tabs(b);b.onglet.icon="Video";b.tab.add_content($(this).data("me").displayContent());tab.displayAll();tab.action.moins.html.children("a").trigger("click")}})}
function Tabs(b){this.nb_max_onglet=b;this.tabs=[];this.tabsSpecial=[];this.action={};this.page_active=this.onglet_active=0;this.html=$("<div />");this.Class;this.len_onglet=2;this.top=10;this.height=80;this.width=95;this.left=0;this.html.data("me",this);Tabs.prototype.init=function(){};Tabs.prototype.addTabsSpecial=function(a){return a instanceof One_tabs?(this.tabsSpecial.push(a),this.action[a.onglet.name]=a.onglet,a.html.data("id",this.tabsSpecial.length-1),this.setId(2),a.html.data("parent",this.html),
!0):!1};Tabs.prototype.removeTabs=function(a){this.tabs[a].onglet.html.remove();this.tabs[a].tab.html.remove();this.tabs.splice(a,1);for(i in this.tabs)this.tabs[i].html.data("id",i)};Tabs.prototype.add_tabs=function(a){return a instanceof One_tabs?(this.tabs.push(a),a.html.data("id",this.tabs.length-1),this.setId(1),a.html.data("parent",this.html),this.tabs.length-1):!1};Tabs.prototype.move=function(a){-1!=this.onglet_active&&this.tabs[this.onglet_active].move(a,this.onglet_active);this.displayAll()};
Tabs.prototype.gets_tabs=function(a){return"int"==typeof a&&a<=this.tabs.nbLine?this.tabs[a]:!1};Tabs.prototype.setId=function(a){if(1==a)for(i in this.tabs)this.tabs[i].tab instanceof Content&&(this.tabs[i].tab.html.attr("id","tabs-"+i),this.tabs[i].setHref(),this.tabs[i].onglet.num=i);else for(i in this.tabsSpecial)this.tabsSpecial[i].tab instanceof Content&&(this.tabsSpecial[i].tab.html.attr("id","tabs-"+i),this.tabsSpecial[i].setHref(),this.tabsSpecial[i].onglet.num=i)};Tabs.prototype.displayAll=
function(){this.display(this.tabs);this.displaySpecial(this.tabsSpecial);$("#tabs").tabs("destroy");$("#tabs").tabs()};Tabs.prototype.display=function(a){for(var b=this.nb_max_onglet*this.page_active,e=0,g=0;e<a.length;e++)a[e].onglet.html.hide();for(;b<a.length;b++){if(g>=this.nb_max_onglet)return!0;$("#tabs_selected").append(a[b].onglet.display());a[b].tab instanceof Content&&b==this.onglet_active&&$("#tabs").append(a[b].tab.display());"undefined"==typeof a[b].onglet.icon?a[b].onglet.link.html(b):
a[b].onglet.link.html(a[b].onglet.icon);a[b].onglet.html.addClass("ui-state-default");$("#tabs ul li").css("height",100/(this.nb_max_onglet+this.tabsSpecial.length)+"%");a[b].onglet.html.show();g++}};Tabs.prototype.displaySpecial=function(a){for(i in a)$("#tabs_selected").append(a[i].onglet.display()),a[i].tab instanceof Content&&($("#tabs").append(a[i].tab.display()),"undefined"!=typeof a[i].tab.Content?a[i].tab.html.html(a[i].tab.Content):a[i].tab.html.html("salut "+i)),"undefined"==typeof a[i].onglet.icon?
a[i].onglet.link.html(i):a[i].onglet.link.html(a[i].onglet.icon),(a[i].onglet instanceof OngletPlus||a[i].onglet instanceof OngletMoin)&&a[i].onglet.html.addClass("ui-state-default"),$("#tabs ul li").css("height",100/(this.nb_max_onglet+this.tabsSpecial.length)+"%")};this.init()}
function One_tabs(b,a,d){this.onglet;this.tab;this.max_move="undefined"==typeof b?90:b;this.Class;this.Color;this.html=$("<div />");One_tabs.prototype.initTabs=function(a,b){this.onglet=b instanceof Onglet||b instanceof OngletPlus||b instanceof OngletMoin?b:new Onglet;this.onglet.html.data("parent",this.html);a instanceof Content||b instanceof OngletPlus||b instanceof OngletMoin?this.tab=a:(this.tab=new Content,this.tab.html.data("parent",this.html))};One_tabs.prototype.move=function(a){this.max_move=
a};One_tabs.prototype.resize_tabs=function(){};One_tabs.prototype.set_icon=function(){};One_tabs.prototype.set_color=function(){};One_tabs.prototype.display=function(){this.html.append(this.onglet.display());this.html.append(this.tab.display());return this.html};One_tabs.prototype.setHref=function(){var a=this.tab.html.attr("id");this.onglet.link.attr("href","#"+a)};this.initTabs(a,d)}
function Onglet(b,a){this.icon=b;this.Color="undefined"==typeof a?"#222299":a;this.html=$("<li />");this.Class;this.size_x;this.size_y;this.num=0;this.link=$("<a />");this.html.data("me",this);this.add_onglet=function(){this.link.data("parent",this.html);this.html.append(this.link);this.link.append(this.icon)};this.display=function(){return this.html};this.add_onglet();this.html.children("a").off();this.html.children("a").on({click:function(){$(this).data("parent").data("parent").data("parent").data("me").onglet_active=
$(this).data("parent").data("me").num;$(this).data("parent").data("parent").data("parent").data("me").displayAll()}})}
function OngletPlus(b,a,d){this.name=a;Onglet.call(this,"+",b,d);if("undefined"==typeof OngletPlus.initialized)for(var e in Onglet.prototype)OngletPlus.prototype[e]=Onglet.prototype[e];OngletPlus.initialized=!0;this.add_onglet();this.html.children("a").off();this.html.children("a").on({click:function(){var a=$(this).data("parent").data("parent").data("parent").data("me");a.page_active+1>=a.tabs.length/a.nb_max_onglet?a.page_active=0:a.page_active++;a.displayAll()}})}
function OngletMoin(b,a,d){this.name=a;this.active=0;Onglet.call(this,"-",b,d);if("undefined"==typeof OngletMoin.initialized)for(var e in Onglet.prototype)OngletMoin.prototype[e]=Onglet.prototype[e];OngletMoin.initialized=!0;this.html.children("a").off();this.html.children("a").on({click:function(){var a=$(this).data("parent").data("parent").data("parent").data("me");-1==this.active?($("#tabs").css("left",-($("#tabs").width()-$("#tabs_selected").width())),this.active=0):0!=a.tabs.length&&($("#tabs").css("left",
"0%"),this.active=-1)}})}function Content(b){this.size_x;this.size_y;this.Color;this.Content=b;this.Class;this.html=$("<div />");Content.prototype.add_content=function(a){this.html.append(a)};Content.prototype.display=function(){return this.html};this.add_content(this.Content)}$("#inscriptionButton").click(function(){$("#inscriptionPage").slideToggle("fold")});function inscription(){$("#inscriptionPage").load("html/inscription.html")}$("#connectionLog").hide();mosaique=[];var connection=!1;
function resizeHeader(){var b=$("header").height();$("header").width();$("#logo").css("font-size",0.9*parseInt(b));$("#connectionButton").css("font-size",0.6*parseInt(b));$("#inscriptionButton").css("font-size",0.6*parseInt(b));$(".Mosaique").css("font-size",0.5*parseInt(b))}function resizeInfoText(){$(".videoInfo").each(function(){var b=this.height();this.children("p").css("font-size",0.5*parseInt(b))})}function resizeIframe(){$("iframe")}
$(window).resize(function(){resizeHeader();$(".Mosaique").trigger("mosaiqueResize");placeMosaique(mosaique)});$("#connectionButton").click(function(){!1==connection&&$("#connectionButton").hide(200,function(){connection=!0;$("#connection").show(200)})});$("header").mouseleave(function(){!0==connection&&$("#connection").hide(200,function(){connection=!1;$("#connectionLog").hide();$("#connectionButton").show(200)})});$("#send").click(function(){$("#pseudo").val();$("#password").val()});
$(document).ready(function(){var b=new Tchat,a=new One_tabs;resizeHeader();resizeInfoText();b.setPos("10%","10%");b.setSize("60%","60%");mosaique.push(new Mosaique(void 0,15,10));tab=new Tabs(2,50);$("#video").append(mosaique[0].html);tab.addTabsSpecial(new One_tabs(void 0,void 0,new OngletPlus("+","plus")));tab.addTabsSpecial(new One_tabs(void 0,void 0,new OngletMoin("-","moins")));a.onglet.icon="tchat";a.tab.add_content(b.getHtml());tab.add_tabs(a);tab.displayAll();$("#tabs").tabs();CreateMosaique(mosaique[0],
30);placeMosaique(mosaique);setEvent();$(window).trigger("resize");inscription()});function message_getMsg(){return this.htmlWrapper}function Message(b,a){this.classWrapper;this.htmlWrapper;this.msg;this.user;Message.prototype.init=message_init;Message.prototype.getMsg=message_getMsg;this.init(b,a)}
function message_init(b,a){if("undefined"==typeof b||"undefined"==typeof a)return!1;this.classWrapper="message";this.htmlWrapper=$("<div />");this.htmlWrapper.append("<span class='usrMsg'>"+b+"</span> : "+a+"");return!0}
function Mosaique(b,a,d){this.mosaiqueClass="Mosaique";this.html=$("<div />");this.html.data("me",this);this.container=[];this.nbCellByLine=a;this.nbLine=d;this.map=[];this.spaceX=this.spaceY=0.9;this.gridspaceX=this.gridspaceY=3;this.maxImportant=this.ecartX=this.ecartY=0;this.fence=[];this.initialize=!1;this.name=$("<div />");this.name.addClass("title");this.html.append(this.name);Mosaique.prototype.addContainer=function(a){return a instanceof Container||a instanceof Stream||a instanceof Video||
a instanceof Folder?(this.container.push(a),this.html.append(a.html),a.html.hide(0),a.html.data("id",this.container.length-1),a.html.data("parent",this),a.setSize(),a.html.resizable(),a.important>this.maxImportant&&(this.maxImportant=a.important),a.html.hover(function(){var a=$('<img class="containerdelete" src="img/delete.png" />');a.data("this",a);a.data("parent",$(this));$(this).append(a);$(".containerdelete").click(function(){$(this).data("parent").data("parent").removeHtmlContainer($(this).data("parent").data("id"))})}),
a.html.mouseleave(function(){$(".containerdelete").remove()}),!0):!1};Mosaique.prototype.removeContainer=function(a){for(var b=0;b<this.nbLine;b++)for(var c=0;c<this.nbCellByLine;c++)this.map[b][c]==a&&(this.map[b][c]=-1);this.container.splice(a,1);for(id in this.container)this.container[id].html.data("id",id)};Mosaique.prototype.removeHtmlContainer=function(a){for(var b=0;b<this.nbLine;b++)for(var c=0;c<this.nbCellByLine;c++)this.map[b][c]==a&&(this.map[b][c]=-1);this.container[a].html.remove();
this.container.splice(a,1);for(id in this.container)this.container[id].html.data("id",id);$(".Mosaique").trigger("mosaiqueResize")};Mosaique.prototype.printMap=function(){for(var a="",b=0;b<this.nbLine;b++){for(var c=0;c<this.nbCellByLine;c++)a+=this.map[b][c]+" ";a+="\n"}alert(a)};Mosaique.prototype.resetMap=function(){for(var a=0;a<this.nbLine;a++)for(var b=0;b<this.nbCellByLine;b++)this.map[a][b]=-1};Mosaique.prototype.initMap=function(){for(var a=0;a<this.nbLine;a++){this.map.push([]);for(var b=
0;b<this.nbCellByLine;b++)this.map[a].push(-1)}};Mosaique.prototype.mosaiquePosition=function(){var a=parseInt($(".MosContainer").css("border-width")),a=2;for(i in this.container)this.container[i].html.css("height",this.cellHeight*this.container[i].important+this.gridspaceY*(this.container[i].important-1)-2*a),this.container[i].html.css("width",this.cellWidth*this.container[i].important+this.gridspaceX*(this.container[i].important-1)-2*a),this.container[i].html.css("top",this.container[i].html.data("y")*
(this.cellHeight+this.gridspaceY)),this.container[i].html.css("left",this.container[i].html.data("x")*(this.cellWidth+this.gridspaceX))};Mosaique.prototype.grillCreation=function(){for(var a=0;a<this.nbLine;a++)for(var b=0;b<this.nbCellByLine;b++){var c=$("<div />");c.data("y",a);c.data("x",b);c.data("parent",this);c.data("this",c);this.html.append(c);c.addClass("grill");this.fence.push(c)}setGrillEvent()};Mosaique.prototype.grillResize=function(){for(i in this.fence)this.fence[i].css("height",this.cellHeight),
this.fence[i].css("width",this.cellWidth),this.fence[i].css("top",this.fence[i].data("y")*(this.cellHeight+this.gridspaceY)),this.fence[i].css("left",this.fence[i].data("x")*(this.cellWidth+this.gridspaceX))};Mosaique.prototype.findPlace=function(a,b,c){"undefined"==typeof c&&(c=0);for("undefined"==typeof b&&(b=0);c<this.nbLine;c++)for(var d=b;d<this.nbCellByLine;d++)if(this.checkPlace(this.container[a].important,d,c,a))return this.takePlace(this.container[a].important,d,c,a),!0;return!1};Mosaique.prototype.containerPosition=
function(){for(var a=this.maxImportant;0<a;){for(id in this.container)this.container[id].important==a&&(this.findPlace(id,this.container[id].html.data("x"),this.container[id].html.data("y"))||this.container[id].html.hide());a--}};Mosaique.prototype.checkPlace=function(a,b,c,d){for(var h=0,f=0,k=c;k<c+a&&k<this.nbLine;k++){for(f=b;f<b+a&&f<this.nbCellByLine;f++){if(-1!=parseInt(this.map[k][f])&&this.map[k][f]!=d)return!1;h=f}f=k}return b+a>this.nbCellByLine||c+a>this.nbLine||"undefined"==typeof this.map[f][h]?
!1:!0};Mosaique.prototype.checkBord=function(a,b,c){return b+a>this.nbCellByLine||c+a>this.nbLine?!1:!0};Mosaique.prototype.takePlace=function(a,b,c,d){for(var h=c;h<c+a&&h<this.nbLine;h++)for(var f=b;f<b+a&&f<this.nbCellByLine;f++)this.map[h][f]=d,this.container[d].html.data("x",b),this.container[d].html.data("y",c)};Mosaique.prototype.takePosition=function(){for(id in this.container)this.container[id].html.fadeIn(5*(id+1)),this.findPlace(id,this.container[id].html.data("x"),this.container[id].html.data("y"))||
this.findPlace(id,0,0)||this.container[id].html.hide()};Mosaique.prototype.initSize=function(){this.cellHeight=this.html.height()/this.nbLine;this.cellWidth=this.html.width()/this.nbCellByLine};Mosaique.prototype.initMosaique=function(){this.html.addClass(this.mosaiqueClass);this.initMap();this.initialize=!0};Mosaique.prototype.displayName=function(a){var b=this.html.position();this.name.html(a);this.name.css("top",b.top-this.name.outerHeight()-120*(b.top/100)+"px")};Mosaique.prototype.draggableCursor=
function(){for(i in this.container){var a=this.container[i].html;a.draggable("option","cursorAt",{top:parseInt(a.height())/2,left:parseInt(a.width())/2})}};Mosaique.prototype.init=function(){this.initSize();this.grillCreation();this.grillResize();this.containerPosition();this.mosaiquePosition();this.draggableCursor();this.displayName("Group")};Mosaique.prototype.resetContent=function(){for(i in this.container)this.container.shift();this.html.html("");this.grillResize();this.html.trigger("mosaiqueResize")};
this.html.on({mosaiqueResize:function(){$(this).data("me").resetMap();$(this).data("me").initSize();$(this).data("me").grillResize();$(this).data("me").takePosition();$(this).data("me").mosaiquePosition();$(this).data("me").draggableCursor();$(this).data("me").displayName("Group")}});this.initMosaique()}function CreateMosaique(b,a){for(b.init();0<a;){var d=new Video;b.addContainer(d);a--}}
function placeMosaique(b){var a=0,d=100/b.length-2*b.length,e=$("#video").width();$(".Mosaique").css("width",e/100*d);for(i in b)b[i].html.css("left",a),a+=b[i].html.outerWidth(!0)}var tabsVisible=!1,connectVisible=!1;
function touchHandler(b){var a=b.changedTouches[0],d="";switch(b.type){case "touchstart":d="mousedown";break;case "touchmove":d="mousemove";break;case "touchend":d="mouseup";break;default:return}var e=document.createEvent("MouseEvent");e.initMouseEvent(d,!0,!0,window,1,a.screenX,a.screenY,a.clientX,a.clientY,!1,!1,!1,!1,0,null);a.target.dispatchEvent(e);b.preventDefault()}
$(function(){document.addEventListener("touchstart",touchHandler,!0);document.addEventListener("touchmove",touchHandler,!0);document.addEventListener("touchend",touchHandler,!0);document.addEventListener("touchcancel",touchHandler,!0)});$(document).ready(function(){$(window).resize(function(){$(".Mosaique").trigger("mosaiqueResize")})});
function Tchat(b,a){this.htmlBox;this.classBox;this.htmlSendMessage;this.classSendMessage;this.htmlReceiveMessage;this.classReceiveMessage;this.allMsg;this.connect;this.usr;this.login="platel_k";Tchat.prototype.init=tchat_init;Tchat.prototype.sendMsg=tchat_sendMsg;Tchat.prototype.recvMsg=tchat_recvMsg;Tchat.prototype.getHtml=tchat_getHtml;Tchat.prototype.addMsg=tchat_addMsg;Tchat.prototype.setPos=tchat_setPosition;Tchat.prototype.setSize=tchat_setSize;Tchat.prototype.displayMsg=tchat_displayMsg;return!0==
this.init(b,a)?!0:!1}
function tchat_init(){this.classBox="tchat";this.classSendMessage="sendMessage";this.classReceiveMessage="recvMessage";this.htmlBox=$("<div />");this.htmlSendMessage=$("<div />");this.htmlReceiveMessage=$("<div />");this.allMsg=[];this.htmlBox.addClass(this.classBox);this.htmlReceiveMessage.addClass(this.classReceiveMessage);this.htmlSendMessage.addClass(this.classSendMessage);this.htmlSendMessage.data("parent",this);this.htmlBox.append(this.htmlReceiveMessage);this.htmlBox.append(this.htmlSendMessage);this.htmlSendMessage.load("html/tchat/send.html",
function(){$(".sendMessage .submit").click(function(){var b=$(".sendMessage .msgInput").parent().parent().parent().data("parent"),a=$(".sendMessage .msgInput").val();$(".sendMessage .msgInput").val("");b.addMsg(a,b.login)})});return!0}function tchat_getHtml(){return this.htmlBox}function tchat_addMsg(b,a){if("undefind"==typeof b)return!1;var d=new Message(a,b);this.allMsg.push(d);this.displayMsg(10);return!0}
function tchat_displayMsg(b){this.htmlReceiveMessage.html("");i=this.allMsg.length-1-b;0>i&&(i=0);for(j=0;0<=i&&j<b&&i<this.allMsg.length;i++)this.htmlReceiveMessage.append(this.allMsg[i].getMsg()),j++}function tchat_setPosition(b,a){this.htmlBox.css("left",b);this.htmlBox.css("top",a)}function tchat_setSize(b,a){this.htmlBox.css("height",b);this.htmlBox.css("width",a)}function tchat_sendMsg(){}function tchat_recvMsg(){}
function User(){User.prototype.init=function(){this.connected=!0};User.prototype.connection=function(){};User.prototype.changeDirectory=function(){}};
